sonar.projectKey=1platformlabs_1platform-content-ai
sonar.organization=1platformlabs

sonar.sources=includes,1platform-content-ai.php
sonar.tests=tests
sonar.php.version=8.3
sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=vendor/**,node_modules/**
sonar.test.exclusions=tests/**

sonar.sourceEncoding=UTF-8
